language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
script: yarn && yarn bootstrap && yarn ci
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
